[2023-03-18 10:29:03,731] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_v3.0.local_to_gcs_task backfill__2021-01-02T06:00:00+00:00 [queued]>
[2023-03-18 10:29:03,780] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_v3.0.local_to_gcs_task backfill__2021-01-02T06:00:00+00:00 [queued]>
[2023-03-18 10:29:03,785] {taskinstance.py:1238} INFO -
--------------------------------------------------------------------------------
[2023-03-18 10:29:03,787] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-03-18 10:29:03,788] {taskinstance.py:1240} INFO -
--------------------------------------------------------------------------------
[2023-03-18 10:29:03,845] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-02 06:00:00+00:00
[2023-03-18 10:29:03,855] {standard_task_runner.py:52} INFO - Started process 2749 to run task
[2023-03-18 10:29:03,865] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_v3.0', 'local_to_gcs_task', 'backfill__2021-01-02T06:00:00+00:00', '--job-id', '167', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplbvn3b0r', '--error-file', '/tmp/tmpjz4bfrpm']
[2023-03-18 10:29:03,871] {standard_task_runner.py:77} INFO - Job 167: Subtask local_to_gcs_task
[2023-03-18 10:29:04,122] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_v3.0.local_to_gcs_task backfill__2021-01-02T06:00:00+00:00 [running]> on host 8cface6de844
[2023-03-18 10:29:04,335] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-03-18 10:29:04,413] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_v3.0
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-01-02T06:00:00+00:00
[2023-03-18 10:29:04,534] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/yellow_tripdata_2021-01.parquet'
[2023-03-18 10:29:04,617] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag_v3.0, task_id=local_to_gcs_task, execution_date=20210102T060000, start_date=20230318T102903, end_date=20230318T102904
[2023-03-18 10:29:04,709] {standard_task_runner.py:92} ERROR - Failed to execute job 167 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/yellow_tripdata_2021-01.parquet'
[2023-03-18 10:29:04,774] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-03-18 10:29:04,974] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-18 10:29:05,057] {dagrun.py:530} ERROR - Marking run <DagRun data_ingestion_gcs_dag_v3.0 @ 2021-01-02 06:00:00+00:00: backfill__2021-01-02T06:00:00+00:00, externally triggered: False> failed
[2023-03-18 10:29:05,066] {dagrun.py:605} INFO - DagRun Finished: dag_id=data_ingestion_gcs_dag_v3.0, execution_date=2021-01-02 06:00:00+00:00, run_id=backfill__2021-01-02T06:00:00+00:00, run_start_date=None, run_end_date=2023-03-18 10:29:05.065399+00:00, run_duration=None, state=failed, external_trigger=False, run_type=backfill, data_interval_start=2021-01-02 06:00:00+00:00, data_interval_end=2021-02-02 06:00:00+00:00, dag_hash=None
[2023-03-18 10:29:05,074] {dagrun.py:749} WARNING - Failed to record duration of <DagRun data_ingestion_gcs_dag_v3.0 @ 2021-01-02 06:00:00+00:00: backfill__2021-01-02T06:00:00+00:00, externally triggered: False>: start_date is not set.
